// Code generated by "stringer -type=nodeType"; DO NOT EDIT

package radix

import "fmt"

const (
	_nodeType_name_0 = "nonNilNodestaticNode"
	_nodeType_name_1 = "capDirNode"
	_nodeType_name_2 = "capAllNode"
)

var (
	_nodeType_index_0 = [...]uint8{0, 10, 20}
	_nodeType_index_1 = [...]uint8{0, 10}
	_nodeType_index_2 = [...]uint8{0, 10}
)

func (i nodeType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _nodeType_name_0[_nodeType_index_0[i]:_nodeType_index_0[i+1]]
	case i == 4:
		return _nodeType_name_1
	case i == 8:
		return _nodeType_name_2
	default:
		return fmt.Sprintf("nodeType(%d)", i)
	}
}
